version: '3.5'

services:
  pf-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./env
    volumes:
      - ./storage:/var/www/pixelfed/storage
      - app-bootstrap:/var/www/pixelfed/bootstrap
      - "./env:/var/www/pixelfed/.env"
    ports:
      - "8080:80"
    depends_on:
      - pf-db
      - pf-redis
    networks:
      - private
      - openbracket

  pf-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./env
    command: php artisan horizon
    volumes:
      - ./storage:/var/www/pixelfed/storage
      - app-bootstrap:/var/www/pixelfed/bootstrap
    depends_on:
      - pf-db
      - pf-redis
    networks:
      - private
      - openbracket
  pf-db:
    restart: always
    image: postgres:14-alpine
    user: "postgres:postgres"
    shm_size: 256mb
    networks:
      - private
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
    volumes:
      - ./User.sql:/docker-entrypoint-initdb.d/User.sql
      - /var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  pf-redis:
    image: redis
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    networks:
      - private
      - openbracket

volumes:
  db_data:
  redis-data:
  app_storage:
  app-bootstrap:


networks:
  private:
    internal: true
  openbracket:
    name: openbracket
    external: true
