version: '3.5'

services:
  pf-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./env
    command: php artisan horizon
    volumes:
      - app_storage:/var/www/pixelfed
      - "./env:/var/www/pixelfed/.env"
    ports:
      - "9999:80"
    depends_on:
      - pf-db
      - pf-redis
    networks:
      - private
      - openbracket

  pf-db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - private
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
    volumes:
      - ./User.sql:/docker-entrypoint-initdb.d/User.sql
      - db_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  pf-redis:
    image: redis
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    networks:
      - private
      - openbracket

volumes:
  db_data:
  redis-data:
  app_storage:


networks:
  private:
    internal: true
  openbracket:
    name: openbracket
    external: true
